import "../styles/app.sass";
import Head from "next/head";
import animContext from "../context/animContext";
import React, { useState } from "react";

//import GSAP
import { gsap } from "gsap/dist/gsap.js";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";

function MyApp({ Component, pageProps }) {
    const [state, setState] = useState({
        windowProps: {},
        setWindowProps: (objWindowProps) => {
            setState({ ...state, windowProps: objWindowProps });
        },
        //Fonction qui gère le scroll automatique vers une page
        scrollToAnim: () => {
            gsap.registerPlugin(ScrollToPlugin);

            const panelsSection = document.querySelector(".panels");
            const panelsContainer = document.querySelector(".panels_container");

            document.querySelectorAll(".anchor").forEach((anchor) => {
                anchor.addEventListener("click", function (e) {
                    e.preventDefault();

                    const targetElem = document.querySelector(e.target.getAttribute("href"));
                    if (targetElem && panelsContainer.isSameNode(targetElem.parentElement)) {
                        const containerOffset = panelsSection.offsetTop + targetElem.offsetLeft;

                        gsap.to(window, {
                            scrollTo: {
                                y: containerOffset,
                                autoKill: false,
                            },
                            duration: 1,
                        });
                    } else {
                        gsap.to(window, {
                            scrollTo: {
                                y: targetElem,
                                autoKill: false,
                            },
                            duration: 1,
                        });
                    }
                });
            });
        },
    });

    return (
        <>
            <animContext.Provider value={state}>
                <Head>
                    <title>Mama-mouv&apos; Coaching</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Component {...pageProps} />
            </animContext.Provider>
        </>
    );
}

export default MyApp;
