import '../styles/index.sass'
import '../styles/app.sass'
import Head from 'next/head'



function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Mama-mouv' Coaching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </>
  )
}

export default MyApp
